version: '3'
services:
  postgres:
    image: postgres:15
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: airflow-redis

  airflow-webserver:
    image: apache/airflow:2.6.3
    container_name: airflow-webserver
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - /Users/marinaguimaraes/Documents/RID157497_Desafio08/dags:/opt/airflow/dags
      - /Users/marinaguimaraes/Documents/RID157497_Desafio08/logs:/opt/airflow/logs
      - /Users/marinaguimaraes/Documents/RID157497_Desafio08/plugins:/opt/airflow/plugins
      - /Users/marinaguimaraes/Documents/RID157497_Desafio08/data:/opt/airflow/data
    command: >
      bash -c "airflow db upgrade &&
               airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
               airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.6.3
    container_name: airflow-scheduler
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - /Users/marinaguimaraes/Documents/RID157497_Desafio08/dags:/opt/airflow/dags
      - /Users/marinaguimaraes/Documents/RID157497_Desafio08/logs:/opt/airflow/logs
      - /Users/marinaguimaraes/Documents/RID157497_Desafio08/plugins:/opt/airflow/plugins
      - /Users/marinaguimaraes/Documents/RID157497_Desafio08/data:/opt/airflow/data
    command: >
      bash -c "airflow scheduler"

volumes:
  postgres-data:

